// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA143gMtcyupHHS6XGRBBUMy6nuT7-t53k',
    appId: '1:840406998562:web:920888740df9c9b7d9b47b',
    messagingSenderId: '840406998562',
    projectId: 'sau-rehab-app',
    authDomain: 'sau-rehab-app.firebaseapp.com',
    storageBucket: 'sau-rehab-app.firebasestorage.app',
    measurementId: 'G-SDHT6TKK9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIMcLxbRP7wg0rl-P92RJgZOn-V0FKeUI',
    appId: '1:840406998562:android:10d58ccd7bc1888ed9b47b',
    messagingSenderId: '840406998562',
    projectId: 'sau-rehab-app',
    storageBucket: 'sau-rehab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyR6Yy6nxKeMUu-8cAKed7eUHUmH5gVE',
    appId: '1:840406998562:ios:ebbf6ec714bc084ed9b47b',
    messagingSenderId: '840406998562',
    projectId: 'sau-rehab-app',
    storageBucket: 'sau-rehab-app.firebasestorage.app',
    iosClientId: '840406998562-693secvbq97dgpeoprcp8mh0ntd769jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehabAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtyR6Yy6nxKeMUu-8cAKed7eUHUmH5gVE',
    appId: '1:840406998562:ios:ebbf6ec714bc084ed9b47b',
    messagingSenderId: '840406998562',
    projectId: 'sau-rehab-app',
    storageBucket: 'sau-rehab-app.firebasestorage.app',
    iosClientId: '840406998562-693secvbq97dgpeoprcp8mh0ntd769jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehabAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA143gMtcyupHHS6XGRBBUMy6nuT7-t53k',
    appId: '1:840406998562:web:aabea1580e17c158d9b47b',
    messagingSenderId: '840406998562',
    projectId: 'sau-rehab-app',
    authDomain: 'sau-rehab-app.firebaseapp.com',
    storageBucket: 'sau-rehab-app.firebasestorage.app',
    measurementId: 'G-3PSG63J8TP',
  );
}
