// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkiaKdpv_hofyvUVqmFsElu3c8O-HWOpQ',
    appId: '1:590337194193:web:c5f1604e2b91ea29752df0',
    messagingSenderId: '590337194193',
    projectId: 'sau-app-7aee1',
    authDomain: 'sau-app-7aee1.firebaseapp.com',
    databaseURL: 'https://sau-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'sau-app-7aee1.firebasestorage.app',
    measurementId: 'G-11V95BDYYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJZVF6KbSkK6wexSoQPxrohEFJ1HkuuxI',
    appId: '1:590337194193:android:c0f0885e0aee544b752df0',
    messagingSenderId: '590337194193',
    projectId: 'sau-app-7aee1',
    databaseURL: 'https://sau-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'sau-app-7aee1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC6-lp5_-Gx0akXfkCAPCN1jnf2nNj9_M',
    appId: '1:590337194193:ios:55706006868afbef752df0',
    messagingSenderId: '590337194193',
    projectId: 'sau-app-7aee1',
    databaseURL: 'https://sau-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'sau-app-7aee1.firebasestorage.app',
    iosBundleId: 'com.example.rehabAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC6-lp5_-Gx0akXfkCAPCN1jnf2nNj9_M',
    appId: '1:590337194193:ios:55706006868afbef752df0',
    messagingSenderId: '590337194193',
    projectId: 'sau-app-7aee1',
    databaseURL: 'https://sau-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'sau-app-7aee1.firebasestorage.app',
    iosBundleId: 'com.example.rehabAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkiaKdpv_hofyvUVqmFsElu3c8O-HWOpQ',
    appId: '1:590337194193:web:7aaf0aa8bee40111752df0',
    messagingSenderId: '590337194193',
    projectId: 'sau-app-7aee1',
    authDomain: 'sau-app-7aee1.firebaseapp.com',
    databaseURL: 'https://sau-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'sau-app-7aee1.firebasestorage.app',
    measurementId: 'G-Y4Q7BKHB68',
  );
}
